export const mobileTheme = {
  color: {
    bg: "#fffafc",
    surface: "#ffffff",
    surfaceMuted: "#f9fafb",
    surfaceSubtle: "#f3f4f6",
    border: "#e5e7eb",
    borderStrong: "#d1d5db",
    text: "#111827",
    textSoft: "#374151",
    textMuted: "#6b7280",
    textFaint: "#9ca3af",
    textOnDark: "#ffffff",
    brandRose: "#9d174d",
    brandRoseStrong: "#ec4899",
    brandRoseSurface: "#fff1f6",
    brandRoseBorder: "#fbcfe8",
    brandRoseBorderSoft: "#f3e8ef",
    brandWarm: "#9C7D5B",
    overlayDark78: "rgba(17,24,39,0.78)",
    overlayDark80: "rgba(17,24,39,0.8)",
    overlayDark86: "rgba(17,24,39,0.86)",
    successSurface: "#ecfdf3",
    successBorder: "#86efac",
    infoSurface: "#eff6ff",
    infoBorder: "#bfdbfe",
    infoText: "#1d4ed8",
    infoTextStrong: "#1e3a8a",
    warnSurface: "#fffbeb",
    warnBorder: "#fcd34d",
    warnBorderStrong: "#fdba74",
    warnBorderSoft: "#fed7aa",
    warnText: "#9a3412",
    warnTextStrong: "#7c2d12",
    danger: "#b91c1c",
    dangerStrong: "#991b1b",
    dangerSurface: "#fef2f2",
    dangerBorder: "#fecaca",
    dangerSurfaceSoft: "#fff1f2",
    dangerBorderSoft: "#fca5a5",
    dangerTextSoft: "#be123c",
    divider: "#f3f4f6",
  },
  opacity: {
    disabled: 0.45,
  },
} as const;
