/** Atelier Dossier design tokens — mirrors web globals.css */
export const atelier = {
  color: {
    parchment: "#faf6f1",
    espresso: "#2c1810",
    terracotta: "#b8734a",
    terracottaLight: "#d4a574",
    roseGold: "#c9a87c",
    sage: "#6b7f6a",
    blush: "#f3e8e2",
    surface: "#fffcf8",
    border: "#e8ddd4",
    borderHover: "#d4c4b8",
    inkStone: "#5c4a3d",
    inkMist: "#8a7968",
    btnFg: "#fffcf8",
    infographicFrame: "#f7f2ec",
    reportPhotoBg: "#ede3d8",
    reportAccentPanel: "#fdf5f0",
    successSurface: "#ecfdf3",
    successBorder: "#86efac",
    successText: "#166534",
    warnSurface: "#fffbeb",
    warnBorder: "#fcd34d",
    warnText: "#9a3412",
    danger: "#b91c1c",
    dangerSurface: "#fef2f2",
    dangerBorder: "#fecaca",
    overlayDark: "rgba(44,24,16,0.75)",
  },
  font: {
    display: "Fraunces_600SemiBold",
    displayRegular: "Fraunces_400Regular",
    body: "InstrumentSans_400Regular",
    bodyMedium: "InstrumentSans_500Medium",
    bodySemibold: "InstrumentSans_600SemiBold",
  },
  space: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  shadow: {
    card: {
      shadowColor: "#2c1810",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    cardHover: {
      shadowColor: "#2c1810",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 20,
      elevation: 8,
    },
  },
  type: {
    foilLabel: { fontSize: 10, letterSpacing: 2.2, textTransform: "uppercase" as const },
    h1: { fontSize: 28, lineHeight: 34 },
    h2: { fontSize: 22, lineHeight: 28 },
    h3: { fontSize: 18, lineHeight: 24 },
    body: { fontSize: 14, lineHeight: 20 },
    bodySm: { fontSize: 13, lineHeight: 18 },
    caption: { fontSize: 11, lineHeight: 16 },
  },
} as const;

/** @deprecated use atelier */
export const mobileTheme = {
  color: {
    bg: atelier.color.parchment,
    surface: atelier.color.surface,
    surfaceMuted: atelier.color.blush,
    surfaceSubtle: atelier.color.infographicFrame,
    border: atelier.color.border,
    borderStrong: atelier.color.borderHover,
    text: atelier.color.espresso,
    textSoft: atelier.color.inkStone,
    textMuted: atelier.color.inkMist,
    textFaint: atelier.color.inkMist,
    textOnDark: atelier.color.btnFg,
    textOnDark80: "rgba(255,255,255,0.8)",
    textOnDark75: "rgba(255,255,255,0.75)",
    textOnDark70: "rgba(255,255,255,0.7)",
    brandRose: atelier.color.terracotta,
    brandRoseStrong: atelier.color.terracottaLight,
    brandRoseSurface: atelier.color.reportAccentPanel,
    brandRoseBorder: atelier.color.terracotta,
    brandRoseBorderSoft: atelier.color.border,
    brandWarm: atelier.color.roseGold,
    overlayDark78: atelier.color.overlayDark,
    overlayDark80: atelier.color.overlayDark,
    overlayDark86: atelier.color.overlayDark,
    overlayDark08: "rgba(44,24,16,0.08)",
    borderDark12: "rgba(44,24,16,0.12)",
    successSurface: atelier.color.successSurface,
    successBorder: atelier.color.successBorder,
    infoSurface: atelier.color.reportAccentPanel,
    infoBorder: atelier.color.border,
    infoText: atelier.color.terracotta,
    infoTextStrong: atelier.color.espresso,
    warnSurface: atelier.color.warnSurface,
    warnBorder: atelier.color.warnBorder,
    warnBorderStrong: atelier.color.warnBorder,
    warnBorderSoft: atelier.color.warnBorder,
    warnText: atelier.color.warnText,
    warnTextStrong: atelier.color.warnText,
    danger: atelier.color.danger,
    dangerStrong: atelier.color.danger,
    dangerSurface: atelier.color.dangerSurface,
    dangerBorder: atelier.color.dangerBorder,
    dangerSurfaceSoft: atelier.color.dangerSurface,
    dangerBorderSoft: atelier.color.dangerBorder,
    dangerTextSoft: atelier.color.danger,
    divider: atelier.color.border,
  },
  opacity: { disabled: 0.45 },
} as const;
